# An action to deploy a new version of the documentation
- name: Deploy Documentation

runs:
  using: "composite"
  steps:
    # simply take the mkdocs tool to deploy the documentation
    #  as there is a builtin feature to update gh-pages branch
    - run: mkdocs gh-deploy --force